---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - variables.yml

  roles:
  - PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Create tag object 'Ansible'
    panos_tag_object:
     provider: '{{ provider }}'
     name: 'Ansible'
     color: 'green'
     comments: 'created by Ansible'
     commit: "False"  

  - name: Create object group 'Ansible-DAG'
    panos_address_group:
     provider: '{{ provider }}'
     name: 'Ansible-DAG'
     dynamic_value: "'First_Tag'"
     tag: ['Ansible']  
     commit: "False"

  - name: Add ansible test fw rule on the firewall
    panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Ansible test'
        description: 'An Ansible test rule for fw rule creation'
        source_zone: ['Internal']
        destination_zone: ['External']
        source_ip: ['1.2.3.4']
        source_user: ['any']
        destination_ip: ['Ansible-DAG']
        category: ['any']
        application: ['web-browsing','ssl']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        tag_name: 'Ansible'
        commit: "False"

  - name: Commit config on firewall
    panos_commit:
     provider: '{{ provider }}'


