---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - variables.yml

  roles:
  - PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: create Internal zone on a firewall
    panos_zone:
     provider: '{{ provider }}'
     zone: 'Internal'
     mode: 'layer3'

  - name: add ethernet1/1 to zone Internal
    panos_interface:
     provider: '{{ provider }}'
     zone_name: 'Internal'
     mode: 'layer3'
     vr_name: 'ansible-VR'
     if_name: "ethernet1/1"
     ip: ["10.1.1.254/24"]
     enable_dhcp: false
     commit: "False"

  - name: create External zone on a firewall
    panos_zone:
     provider: '{{ provider }}'
     zone: 'External'
     mode: 'layer3'

  - name: add ethernet1/2 to zone unfiltered
    panos_interface:
     provider: '{{ provider }}'
     zone_name: 'External'
     mode: 'layer3'
     vr_name: 'ansible-VR'
     if_name: "ethernet1/2"
     ip: ["20.1.1.1/24"]
     enable_dhcp: false
     commit: "False"

  - name: Create default route
    panos_static_route:
     provider: '{{ provider }}'
     name: 'default'
     virtual_router: ansible-VR
     interface: "ethernet1/2"
     nexthop_type: ip-address
     destination: "0.0.0.0/0"
     nexthop: '20.1.1.254'

  - name: Commit config on firewall
    panos_commit:
     provider: '{{ provider }}'


