---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - variables.yml

  roles:
  - PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Remove 'First_Tag' from 1.1.1.1 (will unregister entirely)
    panos_registered_ip:
     provider: '{{ provider }}'
     ips: ['1.1.1.1']
     tags: ['First_Tag']
     state: 'absent'

  - name: Remove 'First_Tag' from 1.1.1.2 (will unregister entirely)
    panos_registered_ip:
     provider: '{{ provider }}'
     ips: ['1.1.1.2']
     tags: ['First_Tag']
     state: 'absent'
